#!/usr/bin/env python3
"""Shared vocabulary for the level generators.

Tools/build_levels.py used to hold all of this plus both level tables, and it
grew to 900 lines. Splitting it was not tidiness: a file that size is awkward
to review, and every level edit produced a diff against the emitter and the
verifier as well. Now the layout tables live in Tools/stage1.py and
Tools/stage2.py, the machinery lives in Tools/build_levels.py, and this module
is the only thing all three share.

Nothing here writes a file. It defines the player's physics, the prefab table,
and one small constructor per kind of thing a level can contain, so a stage
file reads as a list of decisions rather than a list of coordinates.
"""

# ============================================================================
# PHYSICS
#
# These four numbers are the game. Everything else in this file is measured
# against them, and they exist in three places that must agree:
#     Assets/Scripts/PlayerController.cs   (moveSpeed, jumpForce, fall/low mult)
#     Tools/scene_skeleton.unity           (m_GravityScale, and the same fields)
#     here                                 (what the verifier checks layouts on)
#
# Retuned on the evening of 28 Aug. Sprint was removed and its speed became the only speed, and
# the jump was rebuilt around Krin's stage - see the module docstring in
# Tools/stage2.py for why his level forced this.
# ============================================================================
GRAVITY = 9.81
JUMP_FORCE = 13.5
GRAVITY_SCALE = 2.6
FALL_MULTIPLIER = 1.8
WALK_SPEED = 7.5

# Riding is faster and jumps lower. Both matter: the extra speed means a rider
# clears every gap a walker can, but the lower arc means a step-up a walker
# finds trivial can be impossible on a bike - and the bike cannot be dropped
# except at a rack. Any stretch a rider can still be on has to be checked
# against BOTH sets of numbers or the level can softlock.
BIKE_SPEED_MULTIPLIER = 1.5
BIKE_JUMP_MULTIPLIER = 0.78

# A gap may use at most this fraction of the arc that clears it. The missing
# quarter is the difference between "the arithmetic works" and "a person who
# has not memorised this jump lands it".
GAP_SAFETY = 0.75

# A step-up may use at most this fraction of the apex. Higher than it looks:
# 0.70 is what Krin's stage needs, because his +2.32u climb out of the arena is
# 65% of ours. Anything above ~0.55 gets a warning, because a tall step has to
# be taken near the top of the arc where there is very little room left.
STEP_APEX = 0.70
STEP_APEX_WARN = 0.55


def jump_apex(riding=False):
    j = JUMP_FORCE * (BIKE_JUMP_MULTIPLIER if riding else 1.0)
    return j ** 2 / (2.0 * GRAVITY * GRAVITY_SCALE)


def horizontal_reach(step_up, riding=False):
    """Max horizontal distance from take-off to landing `step_up` units higher.

    Rise and fall use different gravity, so this is two parabolas stitched at
    the apex, not one symmetric arc. Returns 0 if the step is higher than the
    jump reaches at all.
    """
    j = JUMP_FORCE * (BIKE_JUMP_MULTIPLIER if riding else 1.0)
    v = WALK_SPEED * (BIKE_SPEED_MULTIPLIER if riding else 1.0)
    g_up = GRAVITY * GRAVITY_SCALE
    g_down = g_up * FALL_MULTIPLIER
    apex = jump_apex(riding)
    if step_up >= apex:
        return 0.0
    t_rise = j / g_up
    t_fall = (2.0 * (apex - step_up) / g_down) ** 0.5
    return v * (t_rise + t_fall)


# ============================================================================
# PREFABS
#
# guid, plus the fileIDs of the components inside each prefab. A PrefabInstance
# override targets one of these fileIDs, so listing a component here is the only
# thing needed to make its fields settable per placement.
#
# Everything below the divider is generated by Tools/make_prefabs.py, where the
# component order is fixed as tf, sr, col, rb, mb, mb2 = go+1 .. go+6. Read the
# fileIDs off that, never guess them.
# ============================================================================
P = {
    "Ground":       dict(guid="6f851581bcfd4db3a0dfd1037b679b9a",
                         go=7900112233440000000, tf=7900112233440000001),
    "Trap":         dict(guid="55752b5a5fb9b304e9683d3333ccb256",
                         go=7474925521374357586, tf=1486569431692548854),
    "Checkpoint":   dict(guid="ac963368351871d439aade9dab6607ad",
                         go=50924625783960144,   tf=5790916828929868942),
    "Goal":         dict(guid="5503e4868b9e32640925196fa63b0062",
                         go=7496332456263003369, tf=8596259638677655486),
    "TrapHidden":   dict(guid="1614458680214683aa039ba0c7e3881b",
                         go=6100000000000000101, tf=6100000000000000102),
    "PlatformFake": dict(guid="00451637c4b84e86886316ae1a3e24a0",
                         go=6100000000000000201, tf=6100000000000000202),
    "TrapSpike":    dict(guid="35c9464f042948d59b07c0d428239327",
                         go=6100000000000000301, tf=6100000000000000302),
    # ---------------------------------------------- Tools/make_prefabs.py
    "Bicycle":      dict(guid="09c5f8c63ef746a6aad3543a707b5a76",
                         go=6100000000000000401, tf=6100000000000000402,
                         mb=6100000000000000406, mb2=6100000000000000407),
    # 'sr' is listed because stage 1 places this prefab twice with two different
    # skins - a dark green lizard and a grey-shirted ajarn - and repainting one
    # instance is a per-placement colour override, not a second prefab. Adding a
    # Teacher.prefab would mean a new GUID, a new asset, and one more thing for
    # a teammate to reimport two days before the deadline.
    "MonitorLizard": dict(guid="39b8caac3b37639b6537358984c7dfad",
                         go=6100000000000000501, tf=6100000000000000502,
                         sr=6100000000000000503, mb=6100000000000000506),
    "Flowerpot":    dict(guid="dd1dc94c849ac13a9ba157347a26b4b8",
                         go=6100000000000000601, tf=6100000000000000602,
                         mb=6100000000000000606),
    "TrafficLane":  dict(guid="44186ecf90d85f489fa6ee3d9989dbca",
                         go=6100000000000000701, tf=6100000000000000702,
                         mb=6100000000000000706),
    "Floodwater":   dict(guid="9371b938c017e6ba23c908b58ebc0fc1",
                         go=6100000000000000801, tf=6100000000000000802,
                         mb=6100000000000000806),
    "FakeGoal":     dict(guid="1b07d9a840bcc7c0192f3fc374031e47",
                         go=6100000000000000901, tf=6100000000000000902,
                         mb=6100000000000000906, mb2=6100000000000000907),
    "Signpost":     dict(guid="9cb749c0cd74ca2344e467dd5fc22e55",
                         go=6100000000000001001, tf=6100000000000001002,
                         mb=6100000000000001006),
    "Teleporter":   dict(guid="c4acadb844b3dc1b692174b42c4ff0a0",
                         go=6100000000000001101, tf=6100000000000001102,
                         mb=6100000000000001106),
    "BikeRack":     dict(guid="db97570d47d73e9857ab1a5c17a3dd69",
                         go=6100000000000001201, tf=6100000000000001202,
                         mb=6100000000000001206, mb2=6100000000000001207),
}

# Things that count toward "traps survived" on the results screen. A bike rack
# is not a hazard and a signpost is not an achievement.
HAZARD_KINDS = {"Trap", "TrapHidden", "TrapSpike", "MonitorLizard", "Flowerpot",
                "TrafficLane", "Floodwater", "Teleporter"}

# Kinds the "is it standing on ground?" rule must skip: these legitimately
# float, span, or sit over a hole by design.
AIRBORNE_KINDS = {"Ground", "Floodwater", "TrafficLane", "Flowerpot",
                  "PlatformFake"}


class Place:
    """One prefab instance. `props` maps 'component.field' -> value, where the
    component key is one of the keys in P[kind] ('mb', 'mb2', ...)."""

    __slots__ = ("kind", "name", "pos", "scale", "props", "note")

    def __init__(self, kind, name, pos, scale=(1, 1, 1), props=None, note=""):
        self.kind = kind
        self.name = name
        self.pos = tuple(pos) if len(pos) == 3 else (pos[0], pos[1], 0)
        self.scale = tuple(scale)
        self.props = props or {}
        self.note = note


# ============================================================================
# CONSTRUCTORS
#
# Every one takes the SURFACE the thing sits on, not the thing's own centre.
# Level tables are written in terms of "on the lobby floor at x=69", and the
# offset from a floor to the middle of the object is a property of the object,
# so it belongs here and not in fifteen call sites.
# ============================================================================

def ground(name, x, y, w, h, flag=""):
    return Place("Ground", name, (x, y), (w, h, 1), note=flag)


def trap(name, x, top):
    # A 0.5u box on the surface: half a unit of a 3.57u arc to clear. Visible,
    # honest, and the thing every later lie is measured against.
    return Place("Trap", name, (x, top + 0.25), (0.5, 0.5, 0.5))


def hidden(name, x, top):
    # A thin floor patch just proud of the surface, so it catches the player
    # however they arrive - walking, landing, or clipping the edge.
    return Place("TrapHidden", name, (x, top + 0.2), (1.2, 0.4, 1))


def kill_floor(name, x, y, w):
    # The same invisible collider, stretched. Krin's KillBlock: the floor of a
    # pit you are not supposed to survive landing in.
    #
    # Flagged "airborne" because it is the one hazard that is SUPPOSED to hang
    # over a hole - the verifier's "is it standing on ground?" rule would
    # otherwise reject every one of them.
    return Place("TrapHidden", name, (x, y), (w, 0.5, 1), note="airborne")


def spike(name, x, top):
    # Rests fully inside the platform. SpikeTrap lifts it 1.1u, clearing the
    # surface by 0.1u - visible, but only a few frames early.
    return Place("TrapSpike", name, (x, top - 0.5), (0.8, 1, 1))


def fake(name, x, top, w=2.0):
    return Place("PlatformFake", name, (x, top - 0.5), (w, 1, 1))


def checkpoint(name, x, top):
    # The respawn position IS this transform, so it sits high enough that the
    # player materialises just above the surface rather than inside it.
    return Place("Checkpoint", name, (x, top + 0.6))


def goal(name, x, top):
    # 2x3 doorway: impossible to miss, and it reads as a door and not a coin.
    return Place("Goal", name, (x, top + 1.5), (2, 3, 1))


def sign(name, x, top, message, latch=False, show=5.5):
    return Place("Signpost", name, (x, top + 0.7), (0.25, 1.4, 1),
                 {"mb.message": message, "mb.showRange": show,
                  "mb.latch": 1 if latch else 0})


def fake_goal(name, x, top, reveal, penalty, sign_text):
    return Place("FakeGoal", name, (x, top + 1.5), (2, 3, 1),
                 {"mb.revealText": reveal, "mb.timePenalty": penalty,
                  "mb2.message": sign_text, "mb2.showRange": 6})


def bicycle(name, x, top, offer=None):
    # Not a boost. Touching one starts a ride only a real rack can end, so a
    # bike has to be placed like a decision: visible early enough to refuse,
    # and never on the only route.
    props = {}
    if offer:
        props["mb.offerMessage"] = offer
    return Place("Bicycle", name, (x, top + 0.95), (0.9, 0.9, 1), props)


def bike_rack(name, x, top, real=True, refused=None, cost=0.0):
    """A place to end the ride, or a convincing photograph of one.

    Real and fake racks are the same prefab, the same size and the same sign,
    and the only difference is one boolean. A fake the player can spot is not
    a fake, it is a warning.
    """
    props = {"mb.isReal": 1 if real else 0}
    if refused:
        props["mb.refusedMessage"] = refused
    if cost:
        props["mb.refusalTimeCost"] = cost
    return Place("BikeRack", name, (x, top + 0.6), (2.6, 1.2, 1), props)


def lizard(name, x, top, chase=7.0, give_up=24.0, trigger=8.0):
    # Was the soi dog. A monitor lizard is what actually comes out of a Lat
    # Krabang klong in the morning, and it is funnier because it is true.
    #
    # chase < WALK_SPEED on purpose: it is a fright, not a wall. On a bike it
    # is nothing, which is the first time the bike pays for itself.
    return Place("MonitorLizard", name, (x, top + 0.35), (1.9, 0.7, 1),
                 {"mb.chaseSpeed": chase, "mb.giveUpDistance": give_up,
                  "mb.triggerDistance": trigger})


def chaser(name, x, top, chase, give_up, trigger=10.0, wind_up=0.6,
           size=(1.0, 1.9), color=(0.32, 0.34, 0.40)):
    """The same ChaserHazard as the lizard, wearing a shirt.

    Stage 1's bike section is gated by this and by nothing else. A chaser at
    9.0 against a 7.5 walk closes 1.5u/s, so the wind-up head start is spent in
    about three seconds and a walker dies in the middle of the corridor; the
    same chaser against an 11.25 ride loses 2.25u/s and is never a threat. That
    difference IS the gate - no key, no script, no rule to explain - and it is
    why the corridor has to be long enough for the arithmetic to finish.

    Sized 1.0 x 1.9 rather than the lizard's 1.9 x 0.7, so the silhouette reads
    as a person from across the screen even before Bun's teacher_1.png is on it.
    """
    return Place("MonitorLizard", name, (x, top + size[1] / 2.0),
                 (size[0], size[1], 1),
                 {"mb.chaseSpeed": chase, "mb.giveUpDistance": give_up,
                  "mb.triggerDistance": trigger, "mb.windUpSeconds": wind_up,
                  "sr.m_Color.r": color[0], "sr.m_Color.g": color[1],
                  "sr.m_Color.b": color[2], "sr.m_Color.a": 1})


def pot(name, x, y, trigger=3.4):
    return Place("Flowerpot", name, (x, y), (0.7, 0.7, 1